/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedItemsRouteImport } from './routes/_protected/items'
import { Route as ProtectedTakenIndexRouteImport } from './routes/_protected/taken/index'
import { Route as ProtectedPlanIndexRouteImport } from './routes/_protected/plan/index'
import { Route as ProtectedNotificatiesIndexRouteImport } from './routes/_protected/notificaties/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCursussenIndexRouteImport } from './routes/_protected/cursussen/index'
import { Route as ProtectedChatIndexRouteImport } from './routes/_protected/chat/index'
import { Route as ProtectedBeheerIndexRouteImport } from './routes/_protected/beheer/index'
import { Route as ProtectedAssistentIndexRouteImport } from './routes/_protected/assistent/index'
import { Route as ProtectedTakenLeerlingIdRouteImport } from './routes/_protected/taken/$leerlingId'
import { Route as ProtectedPlanSubmissionIdRouteImport } from './routes/_protected/plan/$submissionId'
import { Route as ProtectedDashboardLeerlingIdRouteImport } from './routes/_protected/dashboard/$leerlingId'
import { Route as ProtectedCursussenCourseIdRouteImport } from './routes/_protected/cursussen/$courseId'
import { Route as ProtectedPlanBeheerIndexRouteImport } from './routes/_protected/plan/beheer/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedItemsRoute = ProtectedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTakenIndexRoute = ProtectedTakenIndexRouteImport.update({
  id: '/taken/',
  path: '/taken/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlanIndexRoute = ProtectedPlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNotificatiesIndexRoute =
  ProtectedNotificatiesIndexRouteImport.update({
    id: '/notificaties/',
    path: '/notificaties/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCursussenIndexRoute = ProtectedCursussenIndexRouteImport.update({
  id: '/cursussen/',
  path: '/cursussen/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatIndexRoute = ProtectedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBeheerIndexRoute = ProtectedBeheerIndexRouteImport.update({
  id: '/beheer/',
  path: '/beheer/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAssistentIndexRoute = ProtectedAssistentIndexRouteImport.update({
  id: '/assistent/',
  path: '/assistent/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTakenLeerlingIdRoute =
  ProtectedTakenLeerlingIdRouteImport.update({
    id: '/taken/$leerlingId',
    path: '/taken/$leerlingId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPlanSubmissionIdRoute =
  ProtectedPlanSubmissionIdRouteImport.update({
    id: '/plan/$submissionId',
    path: '/plan/$submissionId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardLeerlingIdRoute =
  ProtectedDashboardLeerlingIdRouteImport.update({
    id: '/dashboard/$leerlingId',
    path: '/dashboard/$leerlingId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedCursussenCourseIdRoute =
  ProtectedCursussenCourseIdRouteImport.update({
    id: '/cursussen/$courseId',
    path: '/cursussen/$courseId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPlanBeheerIndexRoute =
  ProtectedPlanBeheerIndexRouteImport.update({
    id: '/plan/beheer/',
    path: '/plan/beheer/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/items': typeof ProtectedItemsRoute
  '/cursussen/$courseId': typeof ProtectedCursussenCourseIdRoute
  '/dashboard/$leerlingId': typeof ProtectedDashboardLeerlingIdRoute
  '/plan/$submissionId': typeof ProtectedPlanSubmissionIdRoute
  '/taken/$leerlingId': typeof ProtectedTakenLeerlingIdRoute
  '/assistent/': typeof ProtectedAssistentIndexRoute
  '/beheer/': typeof ProtectedBeheerIndexRoute
  '/chat/': typeof ProtectedChatIndexRoute
  '/cursussen/': typeof ProtectedCursussenIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/notificaties/': typeof ProtectedNotificatiesIndexRoute
  '/plan/': typeof ProtectedPlanIndexRoute
  '/taken/': typeof ProtectedTakenIndexRoute
  '/plan/beheer/': typeof ProtectedPlanBeheerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/items': typeof ProtectedItemsRoute
  '/cursussen/$courseId': typeof ProtectedCursussenCourseIdRoute
  '/dashboard/$leerlingId': typeof ProtectedDashboardLeerlingIdRoute
  '/plan/$submissionId': typeof ProtectedPlanSubmissionIdRoute
  '/taken/$leerlingId': typeof ProtectedTakenLeerlingIdRoute
  '/assistent': typeof ProtectedAssistentIndexRoute
  '/beheer': typeof ProtectedBeheerIndexRoute
  '/chat': typeof ProtectedChatIndexRoute
  '/cursussen': typeof ProtectedCursussenIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/notificaties': typeof ProtectedNotificatiesIndexRoute
  '/plan': typeof ProtectedPlanIndexRoute
  '/taken': typeof ProtectedTakenIndexRoute
  '/plan/beheer': typeof ProtectedPlanBeheerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/items': typeof ProtectedItemsRoute
  '/_protected/cursussen/$courseId': typeof ProtectedCursussenCourseIdRoute
  '/_protected/dashboard/$leerlingId': typeof ProtectedDashboardLeerlingIdRoute
  '/_protected/plan/$submissionId': typeof ProtectedPlanSubmissionIdRoute
  '/_protected/taken/$leerlingId': typeof ProtectedTakenLeerlingIdRoute
  '/_protected/assistent/': typeof ProtectedAssistentIndexRoute
  '/_protected/beheer/': typeof ProtectedBeheerIndexRoute
  '/_protected/chat/': typeof ProtectedChatIndexRoute
  '/_protected/cursussen/': typeof ProtectedCursussenIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/notificaties/': typeof ProtectedNotificatiesIndexRoute
  '/_protected/plan/': typeof ProtectedPlanIndexRoute
  '/_protected/taken/': typeof ProtectedTakenIndexRoute
  '/_protected/plan/beheer/': typeof ProtectedPlanBeheerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/items'
    | '/cursussen/$courseId'
    | '/dashboard/$leerlingId'
    | '/plan/$submissionId'
    | '/taken/$leerlingId'
    | '/assistent/'
    | '/beheer/'
    | '/chat/'
    | '/cursussen/'
    | '/dashboard/'
    | '/notificaties/'
    | '/plan/'
    | '/taken/'
    | '/plan/beheer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/items'
    | '/cursussen/$courseId'
    | '/dashboard/$leerlingId'
    | '/plan/$submissionId'
    | '/taken/$leerlingId'
    | '/assistent'
    | '/beheer'
    | '/chat'
    | '/cursussen'
    | '/dashboard'
    | '/notificaties'
    | '/plan'
    | '/taken'
    | '/plan/beheer'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/items'
    | '/_protected/cursussen/$courseId'
    | '/_protected/dashboard/$leerlingId'
    | '/_protected/plan/$submissionId'
    | '/_protected/taken/$leerlingId'
    | '/_protected/assistent/'
    | '/_protected/beheer/'
    | '/_protected/chat/'
    | '/_protected/cursussen/'
    | '/_protected/dashboard/'
    | '/_protected/notificaties/'
    | '/_protected/plan/'
    | '/_protected/taken/'
    | '/_protected/plan/beheer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/items': {
      id: '/_protected/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ProtectedItemsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/taken/': {
      id: '/_protected/taken/'
      path: '/taken'
      fullPath: '/taken/'
      preLoaderRoute: typeof ProtectedTakenIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/plan/': {
      id: '/_protected/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof ProtectedPlanIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/notificaties/': {
      id: '/_protected/notificaties/'
      path: '/notificaties'
      fullPath: '/notificaties/'
      preLoaderRoute: typeof ProtectedNotificatiesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cursussen/': {
      id: '/_protected/cursussen/'
      path: '/cursussen'
      fullPath: '/cursussen/'
      preLoaderRoute: typeof ProtectedCursussenIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chat/': {
      id: '/_protected/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ProtectedChatIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/beheer/': {
      id: '/_protected/beheer/'
      path: '/beheer'
      fullPath: '/beheer/'
      preLoaderRoute: typeof ProtectedBeheerIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/assistent/': {
      id: '/_protected/assistent/'
      path: '/assistent'
      fullPath: '/assistent/'
      preLoaderRoute: typeof ProtectedAssistentIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/taken/$leerlingId': {
      id: '/_protected/taken/$leerlingId'
      path: '/taken/$leerlingId'
      fullPath: '/taken/$leerlingId'
      preLoaderRoute: typeof ProtectedTakenLeerlingIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/plan/$submissionId': {
      id: '/_protected/plan/$submissionId'
      path: '/plan/$submissionId'
      fullPath: '/plan/$submissionId'
      preLoaderRoute: typeof ProtectedPlanSubmissionIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/$leerlingId': {
      id: '/_protected/dashboard/$leerlingId'
      path: '/dashboard/$leerlingId'
      fullPath: '/dashboard/$leerlingId'
      preLoaderRoute: typeof ProtectedDashboardLeerlingIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cursussen/$courseId': {
      id: '/_protected/cursussen/$courseId'
      path: '/cursussen/$courseId'
      fullPath: '/cursussen/$courseId'
      preLoaderRoute: typeof ProtectedCursussenCourseIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/plan/beheer/': {
      id: '/_protected/plan/beheer/'
      path: '/plan/beheer'
      fullPath: '/plan/beheer/'
      preLoaderRoute: typeof ProtectedPlanBeheerIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedItemsRoute: typeof ProtectedItemsRoute
  ProtectedCursussenCourseIdRoute: typeof ProtectedCursussenCourseIdRoute
  ProtectedDashboardLeerlingIdRoute: typeof ProtectedDashboardLeerlingIdRoute
  ProtectedPlanSubmissionIdRoute: typeof ProtectedPlanSubmissionIdRoute
  ProtectedTakenLeerlingIdRoute: typeof ProtectedTakenLeerlingIdRoute
  ProtectedAssistentIndexRoute: typeof ProtectedAssistentIndexRoute
  ProtectedBeheerIndexRoute: typeof ProtectedBeheerIndexRoute
  ProtectedChatIndexRoute: typeof ProtectedChatIndexRoute
  ProtectedCursussenIndexRoute: typeof ProtectedCursussenIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedNotificatiesIndexRoute: typeof ProtectedNotificatiesIndexRoute
  ProtectedPlanIndexRoute: typeof ProtectedPlanIndexRoute
  ProtectedTakenIndexRoute: typeof ProtectedTakenIndexRoute
  ProtectedPlanBeheerIndexRoute: typeof ProtectedPlanBeheerIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedItemsRoute: ProtectedItemsRoute,
  ProtectedCursussenCourseIdRoute: ProtectedCursussenCourseIdRoute,
  ProtectedDashboardLeerlingIdRoute: ProtectedDashboardLeerlingIdRoute,
  ProtectedPlanSubmissionIdRoute: ProtectedPlanSubmissionIdRoute,
  ProtectedTakenLeerlingIdRoute: ProtectedTakenLeerlingIdRoute,
  ProtectedAssistentIndexRoute: ProtectedAssistentIndexRoute,
  ProtectedBeheerIndexRoute: ProtectedBeheerIndexRoute,
  ProtectedChatIndexRoute: ProtectedChatIndexRoute,
  ProtectedCursussenIndexRoute: ProtectedCursussenIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedNotificatiesIndexRoute: ProtectedNotificatiesIndexRoute,
  ProtectedPlanIndexRoute: ProtectedPlanIndexRoute,
  ProtectedTakenIndexRoute: ProtectedTakenIndexRoute,
  ProtectedPlanBeheerIndexRoute: ProtectedPlanBeheerIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
